#!/usr/bin/env bash

TEST_ID="lane_self_gravity_fmm"
TAGS="mpi manual benchmark"
CATEGORY="physics"
BUILD_TEST_NAME="regression_tests/cases/lane_self_gravity_fmm"
RUN_DIR_REL="regression_tests/cases/lane_self_gravity_fmm"
CHECK_FUNCTION="check_lane_self_gravity_fmm_case"
RUN_MODE="slurm"
SLURM_NTASKS="128"
SLURM_NODES="8"
SLURM_PARTITION="bigrun"
SLURM_EXCLUSIVE="1"
SLURM_TIME_LIMIT="02:00:00"
RUN_COMMAND='mpirun -np ${SLURM_NTASKS} "${RICH_BIN}"'
