# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# compile CXX with /software/x86_64/5.14.0/openmpi/4.1.6/gcc/12.3.0/bin/mpicxx
CXX_DEFINES = -DMADVORO_WITH_MPI -DRICH_MPI -DSPATIAL_DS_WITH_MPI -DSTORM_CPU_VECTOR_INTERSECTION -DSTORM_DATA_DIR=\"/home/maorm/RICH/source/monte/examples/crooked_pipe\" -DSTORM_WITH_COMPTON -DSTORM_WITH_MPI -D__WITH_IBV -D__WITH_MPI -D__WITH_OFI

CXX_INCLUDES = -I/home/maorm/RICH/source/monte -I/home/maorm/RICH/source/utils -I/home/maorm/RICH/build/rdma128_20260912/candidate_build/storm_dependency_includes -I/home/maorm/RICH/source/3D/tessellation/voronoi -I/home/maorm/RICH/source/3D/tessellation/voronoi/range/finders -I/home/maorm/RICH/source/monte/examples/crooked_pipe -I/home/maorm/RICH/source/monte/deps -I/home/maorm/RICH/source/monte/deps/CMMC/src

CXX_FLAGS =  -fno-omit-frame-pointer -fstrict-aliasing -fno-common -rdynamic -DOMPI_SKIP_MPICXX -O2 -DNDEBUG -g1 -std=c++17 -march=x86-64-v3 -ffp-contract=off -I/home/maorm/opt/libfabric-2.6.0/current/include -fopenmp

