#!/usr/bin/env python3
"""
Generate a Validation & Verification LaTeX report for RICH.

Produces a polished V&V document modeled after a formal report structure:
  - Custom title page with code name and date
  - Table of contents
  - Introduction (purpose, methodology, code overview, test suite overview)
  - Test suite infrastructure description
  - Per-test sections with Problem Description and Results subsections
  - Summary with convergence table and key findings
  - Bibliography

Reuses test metadata and metric readers from generate_test_report.py.

Usage:
    python3 regression_tests/generate_vv_report.py
    python3 regression_tests/generate_vv_report.py --no-compile
    python3 regression_tests/generate_vv_report.py --no-plots
    python3 regression_tests/generate_vv_report.py --output-dir /tmp/report
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Import reusable pieces from the existing report generator
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from generate_test_report import (  # noqa: E402
    BIBLIOGRAPHY,
    METRIC_READERS,
    TEST_CATEGORIES,
    TEST_GROUPS,
    TESTS,
    MetricRow,
    _metrics_table_tex,
    repo_root,
)


# ---------------------------------------------------------------------------
# LaTeX building blocks
# ---------------------------------------------------------------------------

PREAMBLE = r"""\documentclass[11pt,a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amsmath,amssymb}

% Prevent graphicx from loading epstopdf-base (often missing in minimal
% TeX Live installs).
\makeatletter
\@namedef{ver@epstopdf-base.sty}{2024/01/01 stub}
\makeatother

\usepackage{graphicx}
\usepackage[margin=2.5cm]{geometry}
\usepackage{hyperref}
\usepackage{booktabs}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{enumitem}

% ----- page style ----------------------------------------------------------
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\textit{RICH --- Validation \& Verification Report}}
\fancyhead[R]{\small\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\fancypagestyle{plain}{\fancyhf{}\fancyfoot[C]{\thepage}%
  \renewcommand{\headrulewidth}{0pt}}

\hypersetup{
    colorlinks=true,
    linkcolor=blue!60!black,
    urlcolor=blue!60!black,
    citecolor=green!50!black,
}

\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}

\begin{document}

% ==========================================================================
%  Title page
% ==========================================================================
\begin{titlepage}
  \centering
  \vspace*{3cm}
  {\Huge\bfseries Validation \& Verification Report\par}
  \vspace{1.2cm}
  {\LARGE RICH\par}
  \vspace{0.4cm}
  {\large Racah Institute Computational Hydrodynamics\par}
  \vspace{2cm}
  {\large Elad Steinberg, Maor Mizrachi, Itamar Giron\par}
  \vspace{1.5cm}
  {\large\today\par}
  \vfill
  {\small Auto-generated by \texttt{generate\_vv\_report.py}\par}
\end{titlepage}

\tableofcontents
\newpage
"""


INTRODUCTION = r"""
% ==========================================================================
\section{Introduction}
\label{sec:introduction}
% ==========================================================================

RICH (Racah Institute Computational Hydrodynamics) is a multi-physics
simulation code built around Voronoi tessellations.  It solves the
compressible Euler equations in a moving-mesh framework that can operate in
fully Lagrangian, Eulerian, or arbitrary Lagrangian--Eulerian (ALE) mode.
On top of the hydrodynamic core the code provides flux-limited radiation
diffusion (both gray and multigroup), Monte Carlo implicit radiative transfer
with Compton scattering, Newtonian self-gravity through a Barnes--Hut octree,
and adaptive mesh refinement (AMR).  Parallelism is achieved via MPI domain
decomposition using a Hilbert space-filling curve.

As the code grows in capability, a systematic mechanism is needed to guard
against regressions---unintended changes in numerical results introduced by
new development.  This report describes that mechanism: an automated test
suite that exercises each major physics module, compares outputs to known
reference solutions, and reports quantitative pass/fail results.

\subsection{Scope and Approach}

The test suite targets \emph{code verification} in the taxonomy of
Roache~\cite{roache1998} and Oberkampf \& Roy~\cite{oberkampf2010}: each
test compares a numerical solution against an analytical result, a published
benchmark, or a conservation invariant.  Where analytical solutions exist
(e.g.\ the Sod shock tube, Sedov blast wave, Marshak wave), the comparison
is quantitative and the error metric has an explicit numerical threshold.
Where no closed-form solution is available, the test instead monitors
conserved quantities or checks consistency between serial and parallel
execution.

Every test is fully automated and deterministic.  A single shell command
runs the entire suite and returns a non-zero exit code if any test fails,
making the suite suitable for continuous-integration workflows.

\subsection{Test Suite Structure and Interdependencies}

The 27 regression configurations are organised into five categories that
mirror RICH's physics module stack.  Many tests build on capabilities
verified by simpler tests; understanding these dependencies clarifies why
a failure in one area may propagate to others.

\begin{description}
  \item[Part~I --- Pure Hydrodynamics.]
    Exercises the Riemann solver (HLLC), spatial reconstruction, mesh-motion
    modes, and MPI domain decomposition in isolation from radiation or
    gravity.  The Sod shock tube and Sedov blast wave validate the core
    solver on 1-D and 3-D problems; the Gresho and Yee vortex tests
    (at two resolutions each) stress Lagrangian mesh motion and measure
    convergence order; the spherical collapse tests the dedicated spherical
    reconstruction; and the Rayleigh--Taylor instability combines MPI,
    Lagrangian advection, and a gravitational source term.

  \item[Part~II --- Radiation Transport (Diffusion).]
    The four Marshak wave problems form a sequence of increasing complexity:
    uniform density in non-equilibrium, equilibrium limit, non-uniform
    density with a power-law profile, and divergent density on a stretched
    grid.  The Mach~2 radiative shock tests (gray and multigroup) couple
    radiation diffusion to the hydrodynamics verified in Part~I.
    The free--free diffusion suites add grid-resolution convergence and
    cooling-limiter verification.

  \item[Part~III --- Radiation Transport (Monte Carlo).]
    The Till Compton equilibration is solved first with the deterministic
    multigroup solver, then with the IMC Monte Carlo solver, verifying that
    both converge to the same analytic solution.  The Densmore tests exercise
    heterogeneous step-opacity transport with and without random-walk
    acceleration.  The moving-slab benchmark validates frequency-dependent
    transport in a moving medium (single-group and 32-group variants).

  \item[Part~IV --- Self-Gravity.]
    The Lane--Emden polytrope validates the Barnes--Hut octree gravity solver
    coupled to the Lagrangian hydro mesh in a static equilibrium
    configuration.

  \item[Part~V --- Mesh and Infrastructure.]
    The AMR random-refine/coarsen test and Voronoi volume conservation test
    are pure mesh and conservation checks independent of physics.
    The LSQ gradient verification tests (spherical and Cartesian) validate
    the spatial-reconstruction building block that all hydro and radiation
    tests depend upon.
\end{description}

\paragraph{Dependencies between tests.}

\begin{itemize}
  \item \textbf{Physics layering:} radiation-diffusion tests (Part~II)
    rely on hydrodynamics being correct (Part~I); Monte Carlo radiation
    tests (Part~III) additionally depend on the multigroup infrastructure
    shared with diffusion.  Self-gravity (Part~IV) couples to the same
    hydro core.

  \item \textbf{Code-module sharing:} the HLLC Riemann solver is common
    to all hydro and radiation-hydro tests.  The spherical LSQ
    reconstructor feeds into the spherical collapse test; the Cartesian
    LSQ reconstructor underlies all other hydro problems.  MPI
    infrastructure is exercised by Sedov, Gresho (Lagrangian), Yee,
    Rayleigh--Taylor, Lane--Emden, Mach~2, Densmore (MPI variant), and
    the free--free suites.

  \item \textbf{Resolution and complexity ladders:}
    Yee $64^2 \to 128^2$ (convergence order);
    Marshak~1 $\to$ 2 $\to$ 3 $\to$ 4 (progressive difficulty);
    Moving Slab 1-group $\to$ 32-group (spectral resolution);
    Free--free 1-cell $\to$ 32-cell $\to$ 512-cell with and without the
    cooling limiter (spatial convergence and limiter verification).
\end{itemize}

Table~\ref{tab:vv_overview} lists all tests with their execution mode,
CPU count, and mesh type for quick reference.

\subsection{How to Read This Report}

The document proceeds as follows.
Section~\ref{sec:infrastructure} explains how the suite is organised and
how to run it.
Sections~\ref{sec:first_test}--\ref{sec:last_test} present each test
individually: the physical problem, initial and boundary conditions,
pass criteria, and achieved results with comparison plots.
Section~\ref{sec:summary} collects the overall findings.
Table~\ref{tab:vv_overview} below provides a quick reference for the
full test inventory.

\newpage
"""


INFRASTRUCTURE = r"""
% ==========================================================================
\section{Test Suite Infrastructure}
\label{sec:infrastructure}
% ==========================================================================

\subsection{Directory Layout}

The regression test suite lives in the \texttt{regression\_tests/} directory
of the RICH repository.  The key files and directories are:

\begin{verbatim}
regression_tests/
  run_all.sh           # Main driver script
  plot_results.py      # Generates comparison plots
  generate_vv_report.py # Generates this V&V report
  cases/               # Per-test directories
    sod_1d/
      test.cpp         # Test source code
      check_sod.py     # Automated checker
      ...
    sedov_3d_mpi/
    ...
  lib/                 # Shared checker utilities
  plots/               # Generated comparison plots
\end{verbatim}

\subsection{Building}

The RICH build system uses a canonical build wrapper:

\begin{verbatim}
./build_rich.sh <config> --test_name=<run_dir>
\end{verbatim}

\noindent
For example, to build a Sod shock tube test with a GNU Release+MPI
configuration:

\begin{verbatim}
ml openmpi/4.1.6/Intel/OneApi/2024.2.1
./build_rich.sh gnuReleaseMPI --test_name=sod_1d
\end{verbatim}

\subsection{Running Tests}

The full regression suite is run via:

\begin{verbatim}
./regression_tests/run_all.sh
\end{verbatim}

\noindent
Individual tests can be selected with \texttt{--test}:

\begin{verbatim}
./regression_tests/run_all.sh --test sod_1d --config gnuDebugMPI --verbose
\end{verbatim}

MPI binaries are submitted through SLURM on the \texttt{bigrun} partition
with \texttt{--exclusive}.

\subsection{Regression Checking}

Each test directory contains a checker script that parses the simulation
output, computes error metrics, and compares them against explicit numerical
thresholds.  The checker exits with code~0 for success and non-zero for
failure, enabling integration into CI pipelines.  Results are reported as
machine-readable \texttt{KEY=value} log lines.

\newpage
"""

POSTAMBLE = r"""
\end{document}
"""


# ---------------------------------------------------------------------------
# Helper: build the overview table from TESTS metadata
# ---------------------------------------------------------------------------

_TABLE_ROWS: dict[str, tuple[str, str, str, str, str]] = {
    "sod_1d": ("Sod 1D", "Serial", "1", "Eulerian", "Yes"),
    "sedov_3d_mpi": ("Sedov 3D", "MPI", "128", "Lagrangian", "Yes"),
    "gresho_euler": ("Gresho Vortex (Euler)", "Serial", "1", "Eulerian", "Yes"),
    "gresho_lagrangian": ("Gresho Vortex (Lagrangian)", "MPI", "8", "Lagrangian", "Yes"),
    "yee_vortex_64": ("Yee Vortex ($64^2$)", "MPI", "8", "Lagrangian", "Yes"),
    "yee_vortex_128": ("Yee Vortex ($128^2$)", "MPI", "16", "Lagrangian", "No"),
    "spherical_collapse": ("Spherical Collapse", "MPI", "64", "Eulerian", "Yes"),
    "rayleigh_taylor_mpi": ("Rayleigh--Taylor", "MPI", "128", "Lagrangian", "Yes"),
    "marshak_wave_1_diffusion": ("Marshak Wave 1", "Serial", "1", "Eulerian", "Yes"),
    "marshak_wave_2_diffusion": ("Marshak Wave 2", "Serial", "1", "Eulerian", "Yes"),
    "marshak_wave_3_diffusion": ("Marshak Wave 3", "Serial", "1", "Eulerian", "Yes"),
    "marshak_wave_4_diffusion": ("Marshak Wave 4", "Serial", "1", "Eulerian", "Yes"),
    "mach2_diffusion": ("Mach 2 Gray", "MPI", "8", "Eulerian", "Yes"),
    "mach2_multigroup": ("Mach 2 Multigroup", "MPI", "8", "Eulerian", "Yes"),
    "eulerian_diffusion_freefree_suite": ("Gray Free--Free Suite", "MPI", "4--16", "Eulerian", "Yes"),
    "eulerian_diffusion_freefree_multigroup_suite": ("Multigroup Free--Free Suite", "MPI", "4--16", "Eulerian", "Yes"),
    "till_compton": ("Till Compton", "Serial", "1", "Lagrangian", "Yes"),
    "till_compton_mc": ("Till Compton MC", "Serial", "1", "Lagrangian", "Yes"),
    "desmore2012_mc": ("Densmore 2012 MC (MPI)", "MPI", "32", "Eulerian", "Yes"),
    "desmore2012_mc_serial": ("Densmore 2012 MC (serial+RW)", "Serial", "1", "Eulerian", "No"),
    "moving_slab_mc_32": ("Moving Slab MC (32-group)", "Serial", "1", "Lagrangian", "Yes"),
    "lane_self_gravity": ("Lane--Emden", "MPI", "64", "Lagrangian", "Yes"),
    "amr_random": ("AMR Random", "Serial + MPI", "1 / 64", "Lagrangian + AMR", "No"),
    "voronoi_volume": ("Voronoi Volume", "Serial + MPI", "1 / 64", "Static", "No"),
    "spherical_gauss_linear": ("Spherical LSQ Gradient", "Serial", "1", "Static", "No"),
    "cartesian_gauss_linear": ("Cartesian LSQ Gradient", "Serial", "1", "Static", "No"),
}


def _overview_table() -> str:
    """Return a LaTeX summary table listing every test, grouped by category."""
    lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Overview of all regression tests.}",
        r"\label{tab:vv_overview}",
        r"\small",
        r"\begin{tabular}{l l l l l}",
        r"\toprule",
        (r"\textbf{Test} & \textbf{Mode} & \textbf{CPUs} "
         r"& \textbf{Mesh} & \textbf{Plots} \\"),
        r"\midrule",
    ]

    for cat_idx, (cat_name, cat_ids) in enumerate(TEST_CATEGORIES):
        lines.append(r"\multicolumn{5}{l}{\textit{" + cat_name + r"}} \\")
        for entry in cat_ids:
            if entry in TEST_GROUPS:
                _, sub_ids = TEST_GROUPS[entry]
                for tid in sub_ids:
                    row = _TABLE_ROWS[tid]
                    lines.append(r"\quad " + " & ".join(row) + r" \\")
            else:
                row = _TABLE_ROWS[entry]
                lines.append(r"\quad " + " & ".join(row) + r" \\")
        if cat_idx < len(TEST_CATEGORIES) - 1:
            lines.append(r"\addlinespace")

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
        r"\newpage",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-test section (V&V style: Problem Description + Results)
# ---------------------------------------------------------------------------

def _vv_section_for_test(
    test: dict,
    plots_dir: Path,
    cases_dir: Path,
    out_dir: Optional[Path] = None,
    *,
    is_first: bool = False,
    is_last: bool = False,
    level: str = "section",
) -> str:
    """Return the LaTeX source for one test section in V&V style.

    *level* controls heading depth: "section" (default) or "subsection".
    """
    lines: list[str] = []
    tid = test["id"]
    title = test["title"]

    if level == "section":
        sec, subsec = "section", "subsection"
    else:
        sec, subsec = "subsection", "subsubsection"

    lines.append(f"\\{sec}{{{title}}}")
    label = f"sec:{tid}"
    if is_first:
        label = "sec:first_test"
    lines.append(f"\\label{{{label}}}")
    if is_last:
        lines.append(f"\\label{{sec:last_test}}")
    lines.append("")

    lines.append(f"\\{subsec}{{Problem Description}}")
    lines.append("")
    lines.append(test["description"])
    lines.append("")

    ic = test.get("initial_conditions", "")
    bc = test.get("boundary_conditions", "")
    mesh = test.get("mesh_movement", "")
    execution = test.get("execution", "")

    if ic:
        lines.append("\\paragraph{Initial conditions.}")
        lines.append(ic)
        lines.append("")
    if bc:
        lines.append("\\paragraph{Boundary conditions.}")
        lines.append(bc)
        lines.append("")
    if mesh:
        lines.append("\\paragraph{Mesh movement.}")
        lines.append(mesh)
        lines.append("")
    if execution:
        lines.append("\\paragraph{Execution.}")
        lines.append(execution)
        lines.append("")

    lines.append(f"\\{subsec}{{Results}}")
    lines.append("")

    # Pass criteria as the opening of results
    pc = test.get("pass_criteria", "")
    if pc:
        lines.append("\\paragraph{Pass criteria.}")
        lines.append(pc)
        lines.append("")

    # Metrics table
    reader = METRIC_READERS.get(tid)
    if reader is not None:
        metric_rows = reader(cases_dir)
        if metric_rows:
            lines.append("\\paragraph{Achieved results.}")
            lines.append(_metrics_table_tex(metric_rows))
            lines.append("")
        else:
            lines.append(
                "\\textit{No metric output files found --- "
                "run the test suite first.}"
            )
            lines.append("")

    # Plots
    plot_files = test.get("plots", [])
    caption = test.get("plot_caption", "")
    extra_plot_dir = test.get("plot_dir")

    if plot_files:
        available: list[Path] = []
        search_dirs = [plots_dir]
        if extra_plot_dir:
            search_dirs.append(cases_dir / extra_plot_dir)
        for pf in plot_files:
            stem = Path(pf).stem
            for sd in search_dirs:
                pdf_path = sd / f"{stem}.pdf"
                png_path = sd / pf
                if pdf_path.is_file():
                    if out_dir is not None:
                        available.append(
                            Path(os.path.relpath(
                                pdf_path.resolve(), out_dir.resolve()))
                        )
                    else:
                        available.append(pdf_path)
                    break
                elif png_path.is_file():
                    if out_dir is not None:
                        available.append(
                            Path(os.path.relpath(
                                png_path.resolve(), out_dir.resolve()))
                        )
                    else:
                        available.append(png_path)
                    break

        if available:
            lines.append("\\begin{figure}[htbp]")
            lines.append("  \\centering")
            n_plots = len(available)
            if n_plots == 1:
                lines.append(
                    f"  \\includegraphics[width=0.95\\textwidth]"
                    f"{{{available[0]}}}"
                )
            elif n_plots == 2:
                for p in available:
                    lines.append(
                        f"  \\includegraphics[width=0.48\\textwidth]{{{p}}}"
                    )
                    lines.append("  \\hfill")
            else:
                for idx, p in enumerate(available):
                    lines.append(
                        f"  \\includegraphics[width=0.48\\textwidth]{{{p}}}"
                    )
                    if idx % 2 == 0 and idx + 1 < n_plots:
                        lines.append("  \\hfill")
                    elif idx + 1 < n_plots:
                        lines.append("  \\\\[6pt]")
            if caption:
                lines.append(f"  \\caption{{{caption}}}")
            lines.append(f"  \\label{{fig:{tid}}}")
            lines.append("\\end{figure}")
            lines.append("")
        else:
            lines.append(
                "\\textit{Plots not available --- "
                "run the test suite and the plot generator first.}"
            )
            lines.append("")
    else:
        lines.append("\\textit{This test does not produce comparison plots.}")
        lines.append("")

    lines.append("\\newpage")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Summary section
# ---------------------------------------------------------------------------

def _summary_section() -> str:
    """Return a summary/conclusions section."""
    return r"""
\section{Summary}
\label{sec:summary}

This report documents the regression test suite for the RICH hydrodynamics
code.  The suite covers a broad range of physics: compressible hydrodynamics
(Sod shock tube, Sedov blast wave, Gresho vortex, Yee isentropic vortex,
Rayleigh--Taylor instability), radiation transport (Marshak waves, Mach~2
radiative shocks, multigroup diffusion), Monte Carlo radiative transfer
(Densmore 2012, moving slab, Till Compton equilibration), self-gravity
(Lane--Emden polytrope, spherical collapse), and code infrastructure (AMR,
Voronoi volumes, least-squares gradients).

Each test has explicit, quantitative pass criteria with numerical thresholds.
The achieved results are compared to analytical solutions, published
reference data, or conservation invariants, and the pass/fail status is
reported automatically.

The full suite can be run with a single command
(\texttt{./regression\_tests/run\_all.sh}) and produces machine-readable
exit codes suitable for continuous-integration pipelines.

\newpage
"""


# ---------------------------------------------------------------------------
# Appendix: Agentic Coding
# ---------------------------------------------------------------------------

AGENTIC_APPENDIX = r"""
\appendix

\section{Development Process: AI-Assisted Test Suite Construction}
\label{sec:dev_process}

\subsection{Motivation}

Writing a regression suite from scratch is labour-intensive: each test
requires a C++ problem setup, an automated checker with analytical
reference data, a plotting script, and documentation.  Multiplied across
38~test configurations the effort is substantial, yet much of it is
structurally repetitive---parse output, compare to a formula, emit a
pass/fail verdict.  We therefore investigated whether an LLM-based coding
agent could absorb the repetitive implementation work while the developers
retained control over all physics decisions.

\subsection{Tools and Setup}

The work was carried out inside Cursor, an IDE that provides an embedded
LLM agent with direct access to the local file system, terminal, and build
tools.  The agent can read and write files, execute shell commands, submit
Slurm jobs, and inspect their output---all within a conversational
interface.  Project-specific conventions were encoded in machine-readable
rule files (\texttt{.cursor/rules/}) covering the build system
(\texttt{build\_rich.sh}), MPI module loading, Slurm submission patterns,
and coding style.  The agent read these rules at the start of each session,
which eliminated a class of recurring mistakes (wrong partition, missing
modules, non-canonical build invocations).

\subsection{How the Work Was Divided}

Throughout the project the boundary between human and agent responsibilities
remained stable:

\begin{description}
  \item[Developers] chose which physics to test and how---selecting test
    problems, defining initial and boundary conditions, specifying numerical
    parameters (EOS, mesh motion mode, number of MPI ranks), interpreting
    simulation output, and diagnosing failures that required physical
    reasoning.
  \item[Agent] handled the volume work---scanning the C++ source tree for
    available physics modules, drafting \texttt{test.cpp} files, writing
    Python checker and plotting scripts, authoring \LaTeX{} sections for
    this report, and iterating on fixes after each review round.
\end{description}

No parameter value, pass-criteria threshold, or physical setup was chosen by
the agent autonomously; every such decision was made or confirmed by a
developer.

\subsection{Workflow}

The project proceeded in three stages, each with tight feedback loops
between the developers and the agent.

\paragraph{Stage~1: Inventory and planning.}
The agent traversed \texttt{source/} and catalogued the code's physics
modules, mesh types, and boundary-condition options.  The developers then
selected the target test list, prioritised the order (basic hydro first,
radiation and gravity later), and specified which analytical or reference
solutions to use for each problem.

\paragraph{Stage~2: Iterative test implementation.}
For each test the cycle was:
\begin{enumerate}[nosep]
  \item The developers described the problem setup and provided reference
        data or formulae.
  \item The agent drafted the \texttt{test.cpp}, checker script, and plot
        function.
  \item The developers ran the test, inspected the output, and reported
        what needed fixing---wrong boundary condition, incorrect unit
        conversion, missing physics flag, or simply a mismatch with the
        expected solution.
  \item The agent applied the corrections and regenerated the outputs.
\end{enumerate}
A typical test converged after three to five such rounds.  Failures were
almost always physics-level issues (e.g.\ incorrect energy deposition in the
Sedov blast, wrong opacity regime in a Marshak wave, insufficient photon
packets in the Monte Carlo Compton test) rather than syntactic bugs.

\paragraph{Stage~3: Report generation.}
Each test section was written, reviewed for consistency with the actual
results, and revised.  Separate passes addressed plot quality (axis labels,
legend placement, layout) and the infrastructure documentation
(Section~\ref{sec:infrastructure}).  The \LaTeX{} report generator itself
was produced in the same agent-assisted fashion.

\subsection{Observations}

Several practical findings emerged from this process:

\begin{enumerate}
  \item \textbf{Repetitive code is a natural fit.}  The agent was most
    productive on structurally similar tasks---checker scripts, plot
    functions, \LaTeX{} tables---where the pattern is established once and
    replicated with problem-specific parameters.  Physics-level decisions
    remained firmly with the developers.

  \item \textbf{Rule files pay for themselves quickly.}  Encoding build
    commands, Slurm patterns, and module-loading sequences in
    \texttt{.cursor/rules/} prevented the agent from repeatedly
    rediscovering the same project conventions.

  \item \textbf{Fast feedback loops matter.}  Short tests (serial, $< 1$~min)
    could be run, inspected, and corrected within a single conversation.
    Long MPI jobs introduced a natural pause, but the agent could work on
    other tests in the interim.

  \item \textbf{The human bottleneck is reviewing output.}  The agent
    produced code quickly; the limiting step was always the developer
    inspecting simulation results and deciding whether they were physically
    correct.

  \item \textbf{Scale.}  The final suite comprises 38~test configurations,
    ${\sim}\,7\,000$ lines of supporting Python and shell code, and this
    report.  The elapsed calendar time was several working days---compressed
    relative to a fully manual effort by offloading the implementation
    volume to the agent.
\end{enumerate}


% ------------------------------------------------------------------
\subsection{Case Study: Spherical Gauss Gradient and Its Test Suite}
\label{sec:agentic_spherical}
% ------------------------------------------------------------------

The development of the spherical least-squares gradient reconstructor
(\texttt{SphericalLinearGauss3D}) and the family of regression tests that
exercise it illustrates the agent-assisted workflow at its most involved.
The feature touches core numerics (spatial reconstruction), mesh generation,
flux computation, and conservation-law formulation, and ultimately required
four tightly coupled regression tests.  This subsection recounts the
process in detail.

\paragraph{Problem statement.}
RICH's default spatial reconstruction, \texttt{LinearGauss3D}, computes
cell gradients via a weighted least-squares fit in Cartesian coordinates
$(x,y,z)$.  For problems with strong spherical symmetry---converging
shocks, stellar collapse, wind-tunnel implosions---this introduces angular
noise.  The Cartesian gradient basis cannot distinguish ``radial variation''
from ``angular variation''; small angular differences in cell-centre
positions on a nominally spherical shell are treated the same as radial
differences.

The developer posed the question: \emph{can we build a reconstructor that
works in spherical coordinate increments $(\Delta r, \Delta\theta,
\Delta\phi)$ instead of $(\Delta x, \Delta y, \Delta z)$, while remaining
a drop-in replacement for the existing \texttt{SpatialReconstruction3D}
interface?}

\paragraph{Design phase: agent exploration of the existing code.}
The agent began by reading the existing \texttt{LinearGauss3D}
implementation (${\sim}\,1\,200$~lines), tracing how the Gauss--Green /
least-squares gradient was assembled, limited, and converted to face
interpolations.  It then read the \texttt{SpatialReconstruction3D} abstract
interface, the \texttt{Slope3D} data structure, and how
\texttt{ConditionActionFlux1} consumed face-interpolated states.  This
produced a summary of the contract any replacement reconstructor must
satisfy: it must fill \texttt{vector<Slope3D>} in Cartesian derivatives
(because the rest of the hydro loop expects $\partial/\partial x$,
$\partial/\partial y$, $\partial/\partial z$), and it must populate
left/right \texttt{ComputationalCell3D} pairs at every face.

The agent proposed the following architecture:

\begin{enumerate}[nosep]
  \item Map each cell centre and its neighbours to spherical coordinates
    $(r, \theta, \phi)$ about a user-specified origin.
  \item Build the least-squares design matrix using coordinate increments
    $(\Delta r, \Delta\theta, \Delta\phi)$, weighted by
    $A_f / |\Delta\mathbf{x}|^2$ (face area over squared distance).
  \item Express the velocity of each neighbour in its own local spherical
    basis $(\mathbf{e}_r, \mathbf{e}_\theta, \mathbf{e}_\phi)$ before
    differencing, with a sign fix when
    $\mathbf{e}_\phi^{\mathrm{cell}} \cdot
     \mathbf{e}_\phi^{\mathrm{neigh}} < 0$
    (the azimuthal basis flips at $\phi = \pm\pi$).
  \item Solve the $3\times3$ normal equations to obtain derivatives
    $\partial/\partial r$, $\partial/\partial\theta$,
    $\partial/\partial\phi$ for each primitive.
  \item Convert the spherical derivatives to Cartesian storage via the
    inverse Jacobian:
    \[
      \frac{\partial q}{\partial x_j}
      = e_{r,j}\,\frac{\partial q}{\partial r}
      + \frac{e_{\theta,j}}{r}\,\frac{\partial q}{\partial\theta}
      + \frac{e_{\phi,j}}{r\sin\theta}\,
        \frac{\partial q}{\partial\phi}.
    \]
  \item Interpolate face values in $(\Delta r, \Delta\theta, \Delta\phi)$
    space, then convert the velocity back to Cartesian at the face using
    the spherical basis at the face centroid.
\end{enumerate}

The developer approved the design with two additions: a fallback to the
Cartesian path for cells near the poles (where $\sin\theta$ is small and
the azimuthal coordinate degenerates), and the option to apply slope
limiting in the spherical frame.

\paragraph{Implementation: 1\,800 lines of C++.}
The agent wrote the full \texttt{SphericalLinearGauss3D.cpp}
(${\sim}\,1\,800$~lines), including:

\begin{itemize}[nosep]
  \item The core \texttt{calc\_lsq\_slope} function: builds the $3\times3$
    weighted normal matrix, inverts it analytically, and multiplies by the
    right-hand-side vectors for density, pressure, internal energy, velocity
    components, and tracers.
  \item A spherical blended slope limiter mirroring the Cartesian version.
  \item \texttt{coord\_sph\_slope\_to\_cart}: the chain-rule conversion
    described above.
  \item \texttt{Interp}: face interpolation in spherical increments.
  \item \texttt{BuildSlopes} and \texttt{operator()}: the public interface
    consumed by \texttt{ConditionActionFlux1}.
  \item MPI ghost-slope exchange hooks.
\end{itemize}

The developer reviewed the code, corrected two sign errors in the basis
conversion at the poles, and adjusted the degenerate-matrix threshold.

\paragraph{First regression test: spherical gradient accuracy
(\texttt{spherical\_gauss\_linear}).}
To verify that the reconstructor is correct---not just that it
compiles---the agent designed a standalone test.  The idea: initialise
all primitives as \emph{linear functions of spherical coordinates},
\[
  q(r,\theta,\phi) = a_0 + a_1 r + a_2 \theta + a_3 \phi,
\]
with known coefficients.  The spherical LSQ should recover these gradients
exactly (to machine precision for scalars), because the function is in the
span of the basis.  The test:

\begin{enumerate}[nosep]
  \item Generates 8\,000 random Voronoi points in a spherical shell
    $1 \le r \le 2$, plus inner and outer fill regions.
  \item Initialises density, pressure, internal energy, and radial velocity
    as linear-in-$(r,\theta)$ functions (with $a_3=0$ to avoid azimuthal
    wrap issues in this first test).
  \item Runs \texttt{SphericalLinearGauss3D} \emph{and}
    \texttt{LinearGauss3D} on the same mesh and cell data.
  \item For every interior face in the annulus $1.1 \le r \le 1.9$,
    compares the interpolated face value from each reconstructor against
    the exact analytical value.
  \item Reports per-field maximum absolute and relative errors, and writes
    a metrics file with scalar and velocity error summaries for both
    reconstructors.
  \item Passes only if the spherical scalar error is below $10^{-8}$
    \emph{and} strictly smaller than the Cartesian scalar error.
\end{enumerate}

The developer reviewed the test, confirmed the analytical setup, and
suggested adding a companion test (\texttt{cartesian\_gauss\_linear}) that
runs the same comparison on fields that are linear in $(x,y,z)$ instead.
On those fields the Cartesian reconstructor should win, demonstrating that
neither reconstructor is universally better---each is exact for its own
coordinate basis.  The agent implemented this companion test by copying and
adapting the spherical version.

\paragraph{Second regression test: spherical collapse
(\texttt{spherical\_collapse}).}
Gradient accuracy on a static mesh does not guarantee that the
reconstructor works correctly in a real simulation.  The developer
proposed a more demanding test: a dense spherical shell, initialised with
inward radial velocity, collapsing under its own inertia on a 3D Voronoi
mesh.  The key diagnostic: if the reconstruction preserves spherical
symmetry, then the density and velocity should remain nearly uniform at
each radius throughout the collapse.

The agent drafted the test:

\begin{itemize}[nosep]
  \item A cubed-sphere mesh with concentric logarithmic shells, random
    inner-core fill, and random outer fill.
  \item Eulerian hydrodynamics with HLLC Riemann solver and
    \texttt{SphericalLinearGauss3D} reconstruction.
  \item A dense shell ($\rho = 10$, $p = 0.1$) between $r=0.9$ and
    $r=1.0$ with inward radial velocity $v_r = -1$, surrounded by a light
    ambient medium ($\rho = 10^{-3}$).
  \item The simulation runs until the converging shock reaches an inner
    radius $R_{\rm inner}$.
  \item At each output step, cells are binned by radius.  The
    volume-weighted mean density $\bar\rho$ and radial velocity $\bar v_r$
    are computed per shell, and the \emph{scatter}---the mean absolute
    deviation from the shell mean---is tracked.  The maximum scatter over
    the simulation is the reported metric.
  \item Pass criteria: $\max(\rho_{\rm scatter}) < 0.1$ and
    $\max(v_{r,\rm scatter}) < 0.1$.
\end{itemize}

The first run failed with scatter $\sim 0.3$.  The developer identified two
contributing factors.  First, the random inner and outer fill points created
volume defects at the spherical interfaces; the Voronoi cells adjacent to
these random regions had noticeably non-uniform volumes, seeding angular
noise that was amplified by the converging shock.  Second, the face-centroid
radius used for interpolation did not match the symmetry-preserving radial
target, introducing a small radial bias in the reconstructed face states.

The agent then implemented, at the developer's direction:

\begin{enumerate}[nosep]
  \item A reusable mesh helper (\texttt{GenerateSphericalShellMesh3D}) that
    replaces random angular sampling with deterministic Fibonacci-sphere
    directions and replaces random fill regions with deterministic guard
    shells sharing the same angular template.
  \item Mesh diagnostic tools (\texttt{SphericalShellMeshDiagnostics})
    measuring per-shell volume coefficient of variation and max/min volume
    ratio.
  \item New \texttt{SymmetryOptions} for \texttt{SphericalLinearGauss3D}:
    \begin{itemize}[nosep]
      \item \texttt{apply\_radial\_target\_to\_all\_primitives}: shifts the
        interpolation radius from the raw face centroid to the average
        generator radius of the adjacent cells.
      \item \texttt{use\_full\_face\_velocity\_basis}: converts velocity
        using the full spherical basis at the face, not a mixed
        cell/face basis.
      \item \texttt{use\_arc\_length\_lsq\_coordinates}: replaces
        $(\Delta r, \Delta\theta, \Delta\phi)$ with
        $(\Delta r, r\Delta\theta, r\sin\theta\,\Delta\phi)$ in the LSQ,
        giving a locally isotropic length-like basis.
    \end{itemize}
  \item An angular-momentum-conserving flux/update pair
    (\texttt{AngularMomentumFlux3D},
    \texttt{AngularMomentumExtensiveUpdater3D}) that solves the Riemann
    problem in spherical velocity components at each face, using a smooth
    spherical centre-separation direction instead of classifying faces as
    ``radial'' or ``angular.''
\end{enumerate}

With these changes the spherical collapse test passed with density scatter
$\sim 4 \times 10^{-6}$ and velocity scatter $\sim 4 \times 10^{-6}$---six
orders of magnitude below the threshold.

\paragraph{Third regression test: spherical symmetry tools
(\texttt{spherical\_symmetry\_tools}).}
The collapse test is expensive (64~MPI ranks, minutes of wall time).  To
enable fast CI checking of the individual building blocks, the agent created
a lightweight serial test that validates each component in isolation:

\begin{itemize}[nosep]
  \item Builds a low-resolution deterministic spherical mesh and checks
    volume-uniformity metrics.
  \item Runs both legacy and improved reconstruction on an analytic radial
    field and compares radial face-density scatter.
  \item Verifies that the spherical-momentum and angular-momentum flux
    classes match direct spherical-component Riemann solves.
  \item Verifies that the angular-momentum updater applies equal-and-opposite
    spherical-component deltas.
  \item Verifies the angular-momentum recentring and RK-averaging helpers.
\end{itemize}

\paragraph{Summary of the feature arc.}
The full development---from the initial question (``can we do LSQ in
spherical coordinates?'') to four passing regression tests---spanned
several sessions.  The agent wrote ${\sim}\,3\,000$ lines of new C++ (the
reconstructor, mesh helper, flux/update pair, and symmetry-tools test) and
${\sim}\,800$ lines of test setup and checker code.  At every stage the
developer made the physics decisions (which coordinate basis, which
conservation law, which diagnostic metric) and the agent translated those
decisions into code, submitted runs, and iterated on the results.

\newpage
"""


# ---------------------------------------------------------------------------
# Full document assembly
# ---------------------------------------------------------------------------

def generate_vv_tex(
    plots_dir: Path,
    cases_dir: Path,
    out_dir: Optional[Path] = None,
) -> str:
    """Return the full V&V LaTeX document as a string."""
    test_by_id = {t["id"]: t for t in TESTS}
    parts = [PREAMBLE, INTRODUCTION, _overview_table(), INFRASTRUCTURE]

    all_test_ids: list[str] = []
    for _, cat_ids in TEST_CATEGORIES:
        for entry in cat_ids:
            if entry in TEST_GROUPS:
                all_test_ids.extend(TEST_GROUPS[entry][1])
            else:
                all_test_ids.append(entry)
    total_tests = len(all_test_ids)
    global_idx = 0

    for cat_name, cat_ids in TEST_CATEGORIES:
        parts.append(f"\n\\part{{{cat_name}}}\n\\setcounter{{section}}{{0}}\n\\newpage\n")
        for entry in cat_ids:
            if entry in TEST_GROUPS:
                group_title, sub_ids = TEST_GROUPS[entry]
                parts.append(f"\\section{{{group_title}}}")
                parts.append(f"\\label{{sec:{entry}}}")
                if global_idx == 0:
                    parts.append("\\label{sec:first_test}")
                parts.append("")
                for sub_tid in sub_ids:
                    test = test_by_id[sub_tid]
                    parts.append(
                        _vv_section_for_test(
                            test, plots_dir, cases_dir, out_dir,
                            is_first=False,
                            is_last=(global_idx == total_tests - 1),
                            level="subsection",
                        )
                    )
                    global_idx += 1
            else:
                test = test_by_id[entry]
                parts.append(
                    _vv_section_for_test(
                        test, plots_dir, cases_dir, out_dir,
                        is_first=(global_idx == 0),
                        is_last=(global_idx == total_tests - 1),
                    )
                )
                global_idx += 1

    parts.append(_summary_section())
    parts.append(BIBLIOGRAPHY)
    parts.append(AGENTIC_APPENDIX)
    parts.append(POSTAMBLE)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a V&V LaTeX report for the RICH regression test suite."
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Directory to write .tex and .pdf into (default: regression_tests/).",
    )
    parser.add_argument(
        "--no-compile",
        action="store_true",
        help="Only generate the .tex file; do not run pdflatex.",
    )
    parser.add_argument(
        "--no-plots",
        action="store_true",
        help="Skip running plot_results.py (assume plots already exist).",
    )
    parser.add_argument(
        "--plots-dir",
        default=None,
        help="Directory containing plot PNGs (default: regression_tests/plots/).",
    )
    args = parser.parse_args()

    root = repo_root()
    regression_dir = root / "regression_tests"

    if args.output_dir:
        out_dir = Path(args.output_dir)
    else:
        out_dir = regression_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.plots_dir:
        plots_dir = Path(args.plots_dir)
    else:
        plots_dir = regression_dir / "plots"

    # Step 1: generate plots
    if not args.no_plots:
        print("Generating plots via plot_results.py ...")
        plots_dir.mkdir(parents=True, exist_ok=True)
        plot_script = regression_dir / "plot_results.py"
        if plot_script.is_file():
            result = subprocess.run(
                [sys.executable, str(plot_script), "--all",
                 "--output-dir", str(plots_dir)],
                cwd=str(root),
                capture_output=True,
                text=True,
            )
            print(result.stdout)
            if result.returncode != 0:
                print(
                    f"Warning: plot_results.py exited with code "
                    f"{result.returncode}",
                    file=sys.stderr,
                )
                if result.stderr:
                    print(result.stderr, file=sys.stderr)
        else:
            print(
                f"Warning: plot script not found at {plot_script}",
                file=sys.stderr,
            )
    else:
        print("Skipping plot generation (--no-plots).")

    # Step 2: generate .tex
    cases_dir = regression_dir / "cases"
    tex_path = out_dir / "vv_report.tex"
    tex_content = generate_vv_tex(plots_dir, cases_dir, out_dir)
    tex_path.write_text(tex_content, encoding="utf-8")
    print(f"Wrote {tex_path}")

    # Step 3: compile to PDF
    if not args.no_compile:
        pdflatex = shutil.which("pdflatex")
        if pdflatex is None:
            print(
                "pdflatex not found; skipping PDF compilation. "
                "Install a TeX distribution to compile the .tex file.",
                file=sys.stderr,
            )
            return 0

        print("Compiling LaTeX to PDF ...")
        for pass_num in (1, 2):
            result = subprocess.run(
                [pdflatex, "-interaction=nonstopmode",
                 "-output-directory", str(out_dir),
                 str(tex_path)],
                cwd=str(out_dir),
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                print(
                    f"pdflatex pass {pass_num} exited with code "
                    f"{result.returncode}",
                    file=sys.stderr,
                )
                log_file = out_dir / "vv_report.log"
                if log_file.is_file():
                    print(f"See {log_file} for details.", file=sys.stderr)
                if pass_num == 1:
                    return 1

        pdf_path = out_dir / "vv_report.pdf"
        if pdf_path.is_file():
            print(f"PDF generated: {pdf_path}")
        else:
            print(
                "Warning: PDF file not found after compilation.",
                file=sys.stderr,
            )
    else:
        print("Skipping PDF compilation (--no-compile).")

    return 0


if __name__ == "__main__":
    sys.exit(main())
