#ifndef VOROCRUST_EDGE
#define VOROCRUST_EDGE

#include <vector>
#include <string>

#include "VoroCrustUsing.hpp"
#include "VoroCrustVertex.hpp"
#include "VoroCrustFace.hpp"

class VoroCrustEdge
{

public:
    //! \brief the start Vertex of the Edge 
    VoroCrust::Vertex vertex1;
    //! \brief the end Vertex of the Edge 
    VoroCrust::Vertex vertex2; 

    //! \brief the Faces incident to the Edge
    std::vector<VoroCrust::Face> faces;

    //! \brief group faces to surface patches
    std::vector<std::vector<VoroCrust::Face>> divided_faces;
    
    //! \brief Edge index in the plc edges array
    std::size_t index; 
    
    //! \brief true if edge is sharp
    bool isSharp;
    
    //! \brief true if edge is already assigned to a Crease
    bool isCreased; 

    //! \brief the crease index of the edge (if it is sharp) in the PL_Complex creases vector
    std::size_t crease_index;

    /*! \brief Constructs an Edge starting at `v1` and ending at `v2`.
        \param v1 start Vertex of Edge.
        \param v2 end Vertex of Edge.
        \param index_  index of edge in the plc array.
    */
    VoroCrustEdge(VoroCrust::Vertex const& v1, VoroCrust::Vertex const& v2, std::size_t const index_);
    
    /*! \brief if Edge is generated by Vertices v1, v2 in some configuration v1->v2 or v2->v1*/
    bool checkIfEqual(VoroCrust::Vertex const& v1, VoroCrust::Vertex const& v2);

    //! \brief adds a new face to the Edge's Faces vector
    void addFace(VoroCrust::Face const& new_face);

    //! \brief calculates and returns the dihedral angle of the two faces (if there are exactly 2) incident to the Edge.
    double calcDihedralAngle();

    //! \brief orient this to have the same orientation as `edge`
    //! assumes that either one of edge vertices concide
    void orientWithRespectTo(VoroCrust::Edge const& edge);
    
    std::string repr();
};

#endif /* VOROCRUST_EDGE */ 
