find_library(IBVERBS_LIB ibverbs)
find_path(IBVERBS_INCLUDE infiniband/verbs.h)

if(IBVERBS_LIB AND IBVERBS_INCLUDE)
    set(IBV TRUE)
    add_definitions("-D__WITH_IBV")
    message(STATUS "Found libibverbs: ${IBVERBS_LIB}")
    message(STATUS "Found ibverbs headers: ${IBVERBS_INCLUDE}")
    message(STATUS "Defined '__WITH_IBV'")
else()
    message(STATUS "libibverbs not found -- IBV support disabled")
endif()
