set(VTUNE_DIRECTORY "")

# 1) Try EasyBuild environment variable (set by "ml VTune/...")
if(DEFINED ENV{EBROOTVTUNE})
    # EasyBuild VTune has a nested vtune/<version> subdirectory
    file(GLOB _vtune_subdirs "$ENV{EBROOTVTUNE}/vtune/*")
    foreach(_sd IN LISTS _vtune_subdirs)
        if(IS_DIRECTORY "${_sd}/include")
            set(VTUNE_DIRECTORY "${_sd}")
            break()
        endif()
    endforeach()
    if(NOT VTUNE_DIRECTORY)
        set(VTUNE_DIRECTORY "$ENV{EBROOTVTUNE}")
    endif()
endif()

# 2) Fallback: scan PATH for a vtune-related directory
if(NOT VTUNE_DIRECTORY)
    set(path_env $ENV{PATH})
    string(REPLACE ":" ";" path_env_list "${path_env}")

    set(_vtune_prefixes "")
    foreach(dir IN LISTS path_env_list)
        if(dir MATCHES "/vtune")
            string(REGEX REPLACE "/bin(32|64)?$" "" prefix "${dir}")
            list(FIND _vtune_prefixes "${prefix}" _idx)
            if(_idx EQUAL -1)
                list(APPEND _vtune_prefixes "${prefix}")
                message(STATUS "Found VTune candidate: ${prefix}")
            endif()
        endif()
    endforeach()

    list(LENGTH _vtune_prefixes _vtune_count)

    if(_vtune_count EQUAL 1)
        list(GET _vtune_prefixes 0 VTUNE_DIRECTORY)
    elseif(_vtune_count GREATER 1)
        message(FATAL_ERROR "Multiple distinct VTune installations found in PATH: ${_vtune_prefixes}")
    endif()
endif()

if(VTUNE_DIRECTORY)
    message(STATUS "Using VTune: ${VTUNE_DIRECTORY}")
    set(VTUNE_INCLUDE "${VTUNE_DIRECTORY}/include")
    set(VTUNE_LIB_DIRECTORY "${VTUNE_DIRECTORY}/lib64")
else()
    message("No VTUNE installation found (EBROOTVTUNE not set, nothing in PATH)")
endif()
