set(ld_lib_path $ENV{LD_LIBRARY_PATH})

# Split LD_LIBRARY_PATH into a CMake list
string(REPLACE ":" ";" ld_lib_path_list "${ld_lib_path}")

if(NOT PARMETIS_DIRECTORY)
    set(_parmetis_prefixes "")
    foreach(dir IN LISTS ld_lib_path_list)
        if(dir MATCHES "/ParMETIS")
            string(REGEX REPLACE "/lib(64)?$" "" prefix "${dir}")
            list(FIND _parmetis_prefixes "${prefix}" _idx)
            if(_idx EQUAL -1)
                list(APPEND _parmetis_prefixes "${prefix}")
                message(STATUS "Found ParMETIS candidate: ${prefix}")
            endif()
        endif()
    endforeach()

    list(LENGTH _parmetis_prefixes _parmetis_count)

    if(_parmetis_count EQUAL 0)
        message("No ParMETIS installation found in LD_LIBRARY_PATH environment variable")
    elseif(_parmetis_count GREATER 1)
        message(FATAL_ERROR "Multiple distinct ParMETIS installations found in LD_LIBRARY_PATH: ${_parmetis_prefixes}")
    else()
        list(GET _parmetis_prefixes 0 PARMETIS_DIRECTORY)
        message(STATUS "Using ParMETIS: ${PARMETIS_DIRECTORY}")
        set(PARMETIS_INCLUDE "${PARMETIS_DIRECTORY}/include")
        set(PARMETIS_LIB_DIRECTORY "${PARMETIS_DIRECTORY}/lib")
    endif()
endif()

if(NOT METIS_DIRECTORY)
    set(_metis_prefixes "")
    foreach(dir IN LISTS ld_lib_path_list)
        if(dir MATCHES "/METIS")
            string(REGEX REPLACE "/lib(64)?$" "" prefix "${dir}")
            list(FIND _metis_prefixes "${prefix}" _idx)
            if(_idx EQUAL -1)
                list(APPEND _metis_prefixes "${prefix}")
                message(STATUS "Found METIS candidate: ${prefix}")
            endif()
        endif()
    endforeach()

    list(LENGTH _metis_prefixes _metis_count)

    if(_metis_count EQUAL 0)
        message("No METIS installation found in LD_LIBRARY_PATH environment variable")
    elseif(_metis_count GREATER 1)
        message(FATAL_ERROR "Multiple distinct METIS installations found in LD_LIBRARY_PATH: ${_metis_prefixes}")
    else()
        list(GET _metis_prefixes 0 METIS_DIRECTORY)
        message(STATUS "Using METIS: ${METIS_DIRECTORY}")
        set(METIS_INCLUDE "${METIS_DIRECTORY}/include")
        set(METIS_LIB_DIRECTORY "${METIS_DIRECTORY}/lib")
    endif()
endif()

if(NOT GKLIB_DIRECTORY)
    set(_gklib_prefixes "")
    foreach(dir IN LISTS ld_lib_path_list)
        if(dir MATCHES "/GKlib")
            string(REGEX REPLACE "/lib(64)?$" "" prefix "${dir}")
            list(FIND _gklib_prefixes "${prefix}" _idx)
            if(_idx EQUAL -1)
                list(APPEND _gklib_prefixes "${prefix}")
                message(STATUS "Found GKlib candidate: ${prefix}")
            endif()
        endif()
    endforeach()

    list(LENGTH _gklib_prefixes _gklib_count)

    if(_gklib_count EQUAL 0)
        message("No GKLIB installation found in LD_LIBRARY_PATH environment variable")
    elseif(_gklib_count GREATER 1)
        message(FATAL_ERROR "Multiple distinct GKLIB installations found in LD_LIBRARY_PATH: ${_gklib_prefixes}")
    else()
        list(GET _gklib_prefixes 0 GKLIB_DIRECTORY)
        message(STATUS "Using GKlib: ${GKLIB_DIRECTORY}")
        set(GKLIB_INCLUDE "${GKLIB_DIRECTORY}/include")
        set(GKLIB_LIB_DIRECTORY "${GKLIB_DIRECTORY}/lib64")
    endif()
endif()