if(${CONFIG} MATCHES "MPI")
    message(STATUS "With MPI")
    set(MPI 1)
endif()

if(${CONFIG} MATCHES "gnu")
    message(STATUS "With GNU")
    set(GNU 1)
else()
    if(${CONFIG} MATCHES "intel")
        message(STATUS "With Intel")
        set(INTEL 1)
    else()
        # error
        message(FATAL_ERROR "Unknown compiler configuration: ${CONFIG}. Expected 'gnu' or 'intel'.")
    endif()
endif()

if(${CONFIG} MATCHES "Prof")
    message(STATUS "With Prof")
    set(Prof 1)
endif()

if(${CONFIG} MATCHES "Release")
    message(STATUS "Release")
    set(CMAKE_BUILD_TYPE "Release")
else()
    if(${CONFIG} MATCHES "Debug")
        message(STATUS "Debug")
        set(CMAKE_BUILD_TYPE "Debug")
    else()
        # error
        message(FATAL_ERROR "Unknown build type: ${CONFIG}. Expected 'Release' or 'Debug'.")
    endif()
endif()