set(MPI_CC_NAME "mpicc")
set(MPI_CXX_NAME "mpicxx")
set(MPI_Fortran_NAME "mpif90")
set(GNU_CC_NAME "gcc")
set(GNU_CXX_NAME "g++")
set(GNU_Fortran_NAME "gfortran")
set(INTEL_CC_NAME "icx")
set(INTEL_CXX_NAME "icpx")
set(INTEL_Fortran_NAME "ifx")

function(find_executable_path exe_name out_var)
    # Use a unique cache variable name for each call
    string(TOUPPER "${exe_name}" _var_suffix)
    set(_cache_var "FIND_EXECUTABLE_PATH_${_var_suffix}_PATH")

    find_program(${_cache_var} NAMES ${exe_name})
    if(${_cache_var})
        set(${out_var} "${${_cache_var}}" PARENT_SCOPE)
        message(STATUS "Found executable '${exe_name}' at: ${${_cache_var}}")
    else()
        message(FATAL_ERROR "Executable '${exe_name}' not found")
    endif()
endfunction()

if(DEFINED MPI)
    if(DEFINED GNU)
        message(STATUS "GNU, MPI")
        find_executable_path(${MPI_CC_NAME} CMAKE_C_COMPILER)
        find_executable_path(${MPI_CXX_NAME} CMAKE_CXX_COMPILER)
        find_executable_path(${MPI_Fortran_NAME} CMAKE_Fortran_COMPILER)
    endif()
    if(DEFINED INTEL)
        message(STATUS "Intel, MPI")
        find_executable_path(${MPI_CC_NAME} CMAKE_C_COMPILER)
        find_executable_path(${MPI_CXX_NAME} CMAKE_CXX_COMPILER)
        find_executable_path(${MPI_Fortran_NAME} CMAKE_Fortran_COMPILER)
    endif()
else()
    if(DEFINED GNU)
        message(STATUS "GNU, No MPI")
        find_executable_path(${GNU_CC_NAME} CMAKE_C_COMPILER)
        find_executable_path(${GNU_CXX_NAME} CMAKE_CXX_COMPILER)
        find_executable_path(${GNU_Fortran_NAME} CMAKE_Fortran_COMPILER)
    endif()
    if(DEFINED INTEL)
        message(STATUS "Intel, No MPI")
        find_executable_path(${INTEL_CC_NAME} CMAKE_C_COMPILER)
        find_executable_path(${INTEL_CXX_NAME} CMAKE_CXX_COMPILER)
        find_executable_path(${INTEL_Fortran_NAME} CMAKE_Fortran_COMPILER)
    endif()
endif()

message(STATUS "CXX Compiler: " ${CMAKE_CXX_COMPILER})
message(STATUS "C Compiler: " ${CMAKE_C_COMPILER})
message(STATUS "Fortran Compiler: " ${CMAKE_Fortran_COMPILER})
