#!/usr/bin/env bash

TEST_ID="imc_ddmc_review_fixes"
TAGS="serial"
CATEGORY="code_correctness"
BUILD_TEST_NAME="regression_tests/cases/imc_ddmc_review_fixes"
RUN_DIR_REL="regression_tests/cases/imc_ddmc_review_fixes"
BUILD_ARGS="--energy_groups_num=4"
RUN_MODE="direct"
RUN_COMMAND='"${RICH_BIN}"'
CHECK_FUNCTION="check_imc_ddmc_review_fixes_case"
